# provide a name if you wish
# name: btlz-test

networks:
  postgres-net:
    driver: bridge

volumes:
  postgres-vol:
    driver: local
  redis-vol:
    driver: local

services:

  postgres:
    container_name: postgres

    image: postgres:16.1-alpine

    environment:
      - PGPORT=${POSTGRES_PORT}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - PGDATA=/var/lib/postgresql/data/pgdata

    volumes:
      - postgres-vol:/var/lib/postgresql/data

    networks:
      - postgres-net

    expose:
      - ${POSTGRES_PORT}

    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}

    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

    restart: unless-stopped


  app:
    container_name: app

    build:
      context: .
      dockerfile: Dockerfile
      target: prod

    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      REDIS_HOST: redis
      REDIS_PORT: ${REDIS_PORT}
      WB_TARIFFS_BOX_URL: ${WB_TARIFFS_BOX_URL}
      WB_TARIFFS_AUTH_TOKEN: ${WB_TARIFFS_AUTH_TOKEN}
      WB_TARIFFS_QUEUE_NAME: ${WB_TARIFFS_QUEUE_NAME}
      WB_TARIFFS_JOB_ATTEMPTS: ${WB_TARIFFS_JOB_ATTEMPTS}
      WB_TARIFFS_BACKOFF_DELAY_MS: ${WB_TARIFFS_BACKOFF_DELAY_MS}
      WB_TARIFFS_WORKER_CONCURRENCY: ${WB_TARIFFS_WORKER_CONCURRENCY}
      PORT: ${APP_PORT}
      NODE_ENV: production

    ports:
      - ${APP_PORT}:${APP_PORT}

    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - postgres-net

    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: 5

    healthcheck:
      test: [ "CMD-SHELL", "wget -qO- http://localhost:${APP_PORT}/api/v1/health > /dev/null || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

    command: [ "npm", "run", "start" ]
    restart: unless-stopped


  tariffs-worker:
    container_name: tariffs-worker

    build:
      context: .
      dockerfile: Dockerfile
      target: prod

    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      REDIS_HOST: redis
      REDIS_PORT: ${REDIS_PORT}
      WB_TARIFFS_BOX_URL: ${WB_TARIFFS_BOX_URL}
      WB_TARIFFS_AUTH_TOKEN: ${WB_TARIFFS_AUTH_TOKEN}
      WB_TARIFFS_QUEUE_NAME: ${WB_TARIFFS_QUEUE_NAME}
      WB_TARIFFS_JOB_ATTEMPTS: ${WB_TARIFFS_JOB_ATTEMPTS}
      WB_TARIFFS_BACKOFF_DELAY_MS: ${WB_TARIFFS_BACKOFF_DELAY_MS}
      WB_TARIFFS_WORKER_CONCURRENCY: ${WB_TARIFFS_WORKER_CONCURRENCY}
      NODE_ENV: production

    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

    networks:
      - postgres-net

    command: [ "npm", "run", "worker" ]
    restart: always


  tariffs-scheduler-init:
    container_name: tariffs-scheduler-init

    build:
      context: .
      dockerfile: Dockerfile
      target: prod

    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      REDIS_HOST: redis
      REDIS_PORT: ${REDIS_PORT}
      WB_TARIFFS_BOX_URL: ${WB_TARIFFS_BOX_URL}
      WB_TARIFFS_AUTH_TOKEN: ${WB_TARIFFS_AUTH_TOKEN}
      WB_TARIFFS_QUEUE_NAME: ${WB_TARIFFS_QUEUE_NAME}
      WB_TARIFFS_JOB_ATTEMPTS: ${WB_TARIFFS_JOB_ATTEMPTS}
      WB_TARIFFS_BACKOFF_DELAY_MS: ${WB_TARIFFS_BACKOFF_DELAY_MS}
      WB_TARIFFS_WORKER_CONCURRENCY: ${WB_TARIFFS_WORKER_CONCURRENCY}
      NODE_ENV: production

    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

    networks:
      - postgres-net

    command: [ "npm", "run", "scheduler" ]
    restart: "no"


  redis:
    container_name: redis

    image: redis:7.2-alpine

    command: [ "redis-server", "--appendonly", "yes" ]

    volumes:
      - redis-vol:/data

    networks:
      - postgres-net

    expose:
      - ${REDIS_PORT}

    ports:
      - ${REDIS_PORT}:${REDIS_PORT}

    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s

    restart: unless-stopped
